# -*- coding: utf-8 -*-
"""prob_1_lab_AHE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X-qxN_dH8pOf52AX6xzzq29_ciN9Za3o
"""

import cv2
import numpy as np
import glob
import matplotlib.pyplot as plt
import os

"""using the glob library to recursively find all the images"""

def cum_def_fun(img):
    cdf = []
    cdf_r = []
    cdf_g = []
    cdf_b = []
    for i in  range(255):
        cdf.append((((np.shape((np.where(img<=i))))[1])/img.size))
    return cdf

def hist_eq(img):
    img_lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    
    l_channel,a_channel,b_channel = cv2.split(img_lab)
    l_channel_eq = np.copy(l_channel)
    for i in  range(np.max(l_channel)):
        l_channel_eq[np.where(l_channel==i)] = np.floor((((np.shape((np.where(l_channel<=i))))[1])/l_channel.size)*(np.max(l_channel)-np.min(l_channel)))
        merged = cv2.merge([l_channel_eq, a_channel, b_channel])
        eq_img= cv2.cvtColor(merged, cv2.COLOR_LAB2BGR)
    return eq_img

def adap_hist_eq(img, factor): 
    output = np.copy(img)
    AHE_img = np.copy(img)
    m = int((AHE_img.shape[0])/factor)
    n = int((AHE_img.shape[1])/factor-1)
    # a 8X8 channel for equalization
    for i in range(0,AHE_img.shape[0],m):
        for j in range(0, AHE_img.shape[1], n):
            output[i:i+m,j:j+n,:] = hist_eq(AHE_img[i:i+m,j:j+n,:])
            output[i:i+m+20,j:j+n,:] = hist_eq(AHE_img[i:i+m+20,j:j+n,:])
            
    return output

frames =[]
frame = cv2.imread('images/' + str(0) +'.png')
frames = sorted(os.listdir('images/'))
video_output = cv2.VideoWriter('Histo_eq_lab_AHE.avi',cv2.VideoWriter_fourcc(*'DIVX'), 10, (frame.shape[1],frame.shape[0]))

for i in range(25):
    
    image_og = cv2.imread('images/' + str(i) +'.png')
    # cdf = cum_def_fun(image_og)
    eq_img = adap_hist_eq(image_og, 5)
    smooth_img = cv2.GaussianBlur(eq_img,(3,3),1)
    video_output.write(smooth_img)
    # cv2.imshow('1',smooth_img)
    # cv2.waitKey()
    # cv2.destroyAllWindows()